from setuptools import setup
import os


def package_files(directory):
    paths = []
    for (path, directories, filenames) in os.walk(directory):
        for filename in filenames:
            paths.append(os.path.join("..", path, filename))
    return paths


extra_files = package_files("./fcreplay/data")

setup(
    name="fcreplay",
    version="0.9",
    description="Fcreplay python code",
    url="http://github.com/glisignoli/fcreplay",
    author="Gino Lisignoli",
    author_email="glisignoli@gmail.com",
    license="GPL3",
    packages=["fcreplay"],
    package_data={"": extra_files},
    entry_points={"console_scripts": ["fcreplay=fcreplay.__main__:main"]},
    install_requires=[
        "attrs==21.4.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
        "beautifulsoup4==4.10.0; python_version >= '3.1'",
        "bootstrap-flask==2.0.2",
        "cachetools==5.0.0; python_version ~= '3.7'",
        "cerberus==1.3.4",
        "certifi==2021.10.8",
        "charset-normalizer==2.0.12; python_version >= '3'",
        "click==8.0.4; python_version >= '3.6'",
        "cmd2==2.4.0",
        "contextlib2==21.6.0; python_version >= '3.6'",
        "debugpy==1.5.1",
        "docker==5.0.3",
        "docopt==0.6.2",
        "feedgen==0.9.0",
        "flask==2.0.3",
        "flask-cors==3.0.10",
        "flask-sqlalchemy==2.5.1",
        "flask-wtf==1.0.0",
        "google-api-core==2.7.1; python_version >= '3.6'",
        "google-api-python-client==2.41.0",
        "google-auth==2.6.2; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'",
        "google-auth-httplib2==0.1.0",
        "google-auth-oauthlib==0.5.1",
        "googleapis-common-protos==1.56.0; python_version >= '3.6'",
        "greenlet==2.0.0a1; python_version >= '3' and platform_machine == 'aarch64' or (platform_machine == 'ppc64le' or (platform_machine == 'x86_64' or (platform_machine == 'amd64' or (platform_machine == 'AMD64' or (platform_machine == 'win32' or platform_machine == 'WIN32')))))",
        "gunicorn==20.1.0",
        "httplib2==0.20.4; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "i3ipc==2.2.1",
        "idna==3.3; python_version >= '3'",
        "internetarchive==3.0.0",
        "itsdangerous==2.1.1; python_version >= '3.7'",
        "jinja2==3.0.3",
        "jsonpatch==1.32; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
        "jsonpointer==2.2; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "junit-xml==1.9",
        "lxml==4.8.0",
        "markupsafe==2.1.1; python_version >= '3.7'",
        "mouseinfo==0.1.3",
        "oauth2client==4.1.3",
        "oauthlib==3.2.0; python_version >= '3.6'",
        "pillow==9.0.1",
        "progressbar2==4.0.0; python_version >= '3.7'",
        "protobuf==3.20.0rc2; python_version >= '3.7'",
        "psycopg2==2.9.3",
        "pyasn1==0.4.8",
        "pyasn1-modules==0.2.8",
        "pyautogui==0.9.53",
        "pygetwindow==0.0.9",
        "pymsgbox==1.0.9",
        "pyparsing==3.0.7; python_version >= '3.1'",
        "pyperclip==1.8.2",
        "pyrect==0.2.0",
        "pyscreeze==0.1.28",
        "python-dateutil==2.8.2; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "python-logging-loki==0.3.1",
        "python-utils==3.1.0; python_version >= '3.7'",
        "python-xlib==0.31",
        "python3-xlib==0.15",
        "pytweening==1.0.4",
        "pytz==2021.3",
        "pyyaml==6.0",
        "requests==2.27.1",
        "requests-oauthlib==1.3.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "retrying==1.3.3",
        "rfc3339==6.2",
        "rsa==4.8; python_version >= '3.6'",
        "schedule==1.1.0",
        "schema==0.7.5",
        "six==1.16.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "soupsieve==2.3.1; python_version >= '3.6'",
        "sqlalchemy==1.4.32",
        "sqlalchemy-utils==0.38.2",
        "tqdm==4.63.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "uritemplate==4.1.1; python_version >= '3.6'",
        "urllib3==1.26.9",
        "wcwidth==0.2.5",
        "websocket-client==1.3.1; python_version >= '3.6'",
        "werkzeug==2.0.3",
        "wtforms==3.0.1",
    ],
    dependency_links=[
        "git+https://github.com/glisignoli/pylinkvalidator@9af220529dc56a1b16998d0c5bf9e37c45d31448#egg=pylinkvalidator",
        "git+https://github.com/tokland/youtube-upload.git@6a30b55d0fd4976571a5b9b34c01fd41cec49c7a#egg=youtube-upload",
    ],
    zip_safe=False,
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Programming Language :: Python :: 3.10",
        "Topic :: Utilities",
    ],
)
